M48
; DRILL file {KiCad 7.0.11} date Mon Mar 31 22:51:49 2025
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-31T22:51:49+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X5.7917Y-4.2675
X6.0193Y-4.2675
T2
X5.4331Y-3.4646
X5.4331Y-4.4094
X6.378Y-3.4646
X6.378Y-4.4094
M30
